[package]
name = "iron"
version = "0.1.0"
authors = ["Eoin Halligan <ehalligan12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
stacktrace = "0.2"
